-- 혜택 테이블

select * from card_benefit;
TRUNCATE table card_benefit;

delete from card_benefit where BENEFIT_ID = 8;

-- KB국민 My WE:SH 카드
INSERT INTO card_benefit (BENEFIT_ID, CARD_ID, BENEFIT_TYPE, BENEFIT_TITLE, BENEFIT_VALUE, CREATED_AT, UPDATED_AT)
VALUES (CARD_BENEFIT_SEQ.nextval, 1, '포인트적립', 'KB Pay 할인', '10%', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO card_benefit (BENEFIT_ID, CARD_ID, BENEFIT_TYPE, BENEFIT_TITLE, BENEFIT_VALUE, CREATED_AT, UPDATED_AT)
VALUES (CARD_BENEFIT_SEQ.nextval, 1, '음식', '음식점 할인', '10%', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO card_benefit (BENEFIT_ID, CARD_ID, BENEFIT_TYPE, BENEFIT_TITLE, BENEFIT_VALUE, CREATED_AT, UPDATED_AT)
VALUES (CARD_BENEFIT_SEQ.nextval, 1, '편의점', '편의점 할인', '10%', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO card_benefit (BENEFIT_ID, CARD_ID, BENEFIT_TYPE, BENEFIT_TITLE, BENEFIT_VALUE, CREATED_AT, UPDATED_AT)
VALUES (CARD_BENEFIT_SEQ.nextval, 1, '디지털구독', 'OTT 할인', '30%', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO card_benefit (BENEFIT_ID, CARD_ID, BENEFIT_TYPE, BENEFIT_TITLE, BENEFIT_VALUE, CREATED_AT, UPDATED_AT)
VALUES (CARD_BENEFIT_SEQ.nextval, 1, '음식', '배달 할인', '5%', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO card_benefit (BENEFIT_ID, CARD_ID, BENEFIT_TYPE, BENEFIT_TITLE, BENEFIT_VALUE, CREATED_AT, UPDATED_AT)
VALUES (CARD_BENEFIT_SEQ.nextval, 1, '여가', '영화관 할인', '30%', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO card_benefit (BENEFIT_ID, CARD_ID, BENEFIT_TYPE, BENEFIT_TITLE, BENEFIT_VALUE, CREATED_AT, UPDATED_AT)
VALUES (CARD_BENEFIT_SEQ.nextval, 1, '쇼핑', '올리브 영 할인', '5%', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


-- 현대 M카드 
INSERT INTO card_benefit (BENEFIT_ID, CARD_ID, BENEFIT_TYPE, BENEFIT_TITLE, BENEFIT_VALUE, CREATED_AT, UPDATED_AT)
VALUES (CARD_BENEFIT_SEQ.nextval, 2, '음식', '일반음식점 할인', '5%', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO card_benefit (BENEFIT_ID, CARD_ID, BENEFIT_TYPE, BENEFIT_TITLE, BENEFIT_VALUE, CREATED_AT, UPDATED_AT)
VALUES (CARD_BENEFIT_SEQ.nextval, 2, '쇼핑', '쇼핑몰 할인', '5%', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO card_benefit (BENEFIT_ID, CARD_ID, BENEFIT_TYPE, BENEFIT_TITLE, BENEFIT_VALUE, CREATED_AT, UPDATED_AT)
VALUES (CARD_BENEFIT_SEQ.nextval, 2, '가맹점', '국내외 가맹점 할인', '1.5%', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO card_benefit (BENEFIT_ID, CARD_ID, BENEFIT_TYPE, BENEFIT_TITLE, BENEFIT_VALUE, CREATED_AT, UPDATED_AT)
VALUES (CARD_BENEFIT_SEQ.nextval, 2, '가맹점', '해외 가맹점 할인', '5%', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 삼성 iD SIMPLE카드
INSERT INTO card_benefit (BENEFIT_ID, CARD_ID, BENEFIT_TYPE, BENEFIT_TITLE, BENEFIT_VALUE, CREATED_AT, UPDATED_AT)
VALUES (CARD_BENEFIT_SEQ.nextval, 3, '가맹점', '국내외 가맹점 할인', '0.7%', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO card_benefit (BENEFIT_ID, CARD_ID, BENEFIT_TYPE, BENEFIT_TITLE, BENEFIT_VALUE, CREATED_AT, UPDATED_AT)
VALUES (CARD_BENEFIT_SEQ.nextval, 3, '가맹점', '국내외 가맹점 할인', '1%', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO card_benefit (BENEFIT_ID, CARD_ID, BENEFIT_TYPE, BENEFIT_TITLE, BENEFIT_VALUE, CREATED_AT, UPDATED_AT)
VALUES (CARD_BENEFIT_SEQ.nextval, 3, '쇼핑', '온라인 쇼핑몰 멤버십 할인', '50%', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO card_benefit (BENEFIT_ID, CARD_ID, BENEFIT_TYPE, BENEFIT_TITLE, BENEFIT_VALUE, CREATED_AT, UPDATED_AT)
VALUES (CARD_BENEFIT_SEQ.nextval, 3, '영화', '영화 할인', '3,000원', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


-- 농협 별다줄카드
INSERT INTO card_benefit (BENEFIT_ID, CARD_ID, BENEFIT_TYPE, BENEFIT_TITLE, BENEFIT_VALUE, CREATED_AT, UPDATED_AT)
VALUES (CARD_BENEFIT_SEQ.nextval, 4, '쇼핑', '국내 온라인 전 가맹점 청구 할인', '7%', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO card_benefit (BENEFIT_ID, CARD_ID, BENEFIT_TYPE, BENEFIT_TITLE, BENEFIT_VALUE, CREATED_AT, UPDATED_AT)
VALUES (CARD_BENEFIT_SEQ.nextval, 4, '할인', 'FLEX, RE-SELL, FUN 가맹점 청구 할인', '14%', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO card_benefit (BENEFIT_ID, CARD_ID, BENEFIT_TYPE, BENEFIT_TITLE, BENEFIT_VALUE, CREATED_AT, UPDATED_AT)
VALUES (CARD_BENEFIT_SEQ.nextval, 4, '생활', '6대 생활업종 청구 할인', '5%', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO card_benefit (BENEFIT_ID, CARD_ID, BENEFIT_TYPE, BENEFIT_TITLE, BENEFIT_VALUE, CREATED_AT, UPDATED_AT)
VALUES (CARD_BENEFIT_SEQ.nextval, 4, '항공', '국제공항 라운지 무료 이용', '연 2회', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO card_benefit (BENEFIT_ID, CARD_ID, BENEFIT_TYPE, BENEFIT_TITLE, BENEFIT_VALUE, CREATED_AT, UPDATED_AT)
VALUES (CARD_BENEFIT_SEQ.nextval, 4, '여가', '전국 주요 놀이공원 현장 할인', '최대 50%', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 신한 처음카드
INSERT INTO card_benefit (BENEFIT_ID, CARD_ID, BENEFIT_TYPE, BENEFIT_TITLE, BENEFIT_VALUE, CREATED_AT, UPDATED_AT)
VALUES (CARD_BENEFIT_SEQ.nextval, 5, '통신', '통신비 할인', '5%', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO card_benefit (BENEFIT_ID, CARD_ID, BENEFIT_TYPE, BENEFIT_TITLE, BENEFIT_VALUE, CREATED_AT, UPDATED_AT)
VALUES (CARD_BENEFIT_SEQ.nextval, 5, '음식점', '음식점 할인', '5%', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO card_benefit (BENEFIT_ID, CARD_ID, BENEFIT_TYPE, BENEFIT_TITLE, BENEFIT_VALUE, CREATED_AT, UPDATED_AT)
VALUES (CARD_BENEFIT_SEQ.nextval, 5, '적립', '음식점 포인트 적립', '5%', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO card_benefit (BENEFIT_ID, CARD_ID, BENEFIT_TYPE, BENEFIT_TITLE, BENEFIT_VALUE, CREATED_AT, UPDATED_AT)
VALUES (CARD_BENEFIT_SEQ.nextval, 5, '생활', '카페 포인트 적립', '5%', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO card_benefit (BENEFIT_ID, CARD_ID, BENEFIT_TYPE, BENEFIT_TITLE, BENEFIT_VALUE, CREATED_AT, UPDATED_AT)
VALUES (CARD_BENEFIT_SEQ.nextval, 5, '편의점', '편의점 포인트 적립', '5%', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO card_benefit (BENEFIT_ID, CARD_ID, BENEFIT_TYPE, BENEFIT_TITLE, BENEFIT_VALUE, CREATED_AT, UPDATED_AT)
VALUES (CARD_BENEFIT_SEQ.nextval, 5, '생활', '일상 속 (생활, 여행, 패션) 적립', '5%', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO card_benefit (BENEFIT_ID, CARD_ID, BENEFIT_TYPE, BENEFIT_TITLE, BENEFIT_VALUE, CREATED_AT, UPDATED_AT)
VALUES (CARD_BENEFIT_SEQ.nextval, 5, '통신', '정기결제 (통신, OTT, 멤버십) 적립', '최대 20%', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 하나 K-PASS

INSERT INTO card_benefit (BENEFIT_ID, CARD_ID, BENEFIT_TYPE, BENEFIT_TITLE, BENEFIT_VALUE, CREATED_AT, UPDATED_AT)
VALUES (CARD_BENEFIT_SEQ.nextval, 6, '교통', '버스/지하철', '10% 캐시백', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO card_benefit (BENEFIT_ID, CARD_ID, BENEFIT_TYPE, BENEFIT_TITLE, BENEFIT_VALUE, CREATED_AT, UPDATED_AT)
VALUES (CARD_BENEFIT_SEQ.nextval, 6, '의료', '다이소/올리브영', '1% 캐시백', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO card_benefit (BENEFIT_ID, CARD_ID, BENEFIT_TYPE, BENEFIT_TITLE, BENEFIT_VALUE, CREATED_AT, UPDATED_AT)
VALUES (CARD_BENEFIT_SEQ.nextval, 6, '카페', '스타벅스/커피빈', '1% 캐시백', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 국민내일배움카드(체크)
INSERT INTO card_benefit (BENEFIT_ID, CARD_ID, BENEFIT_TYPE, BENEFIT_TITLE, BENEFIT_VALUE, CREATED_AT, UPDATED_AT)
VALUES (CARD_BENEFIT_SEQ.nextval, 7, '주유', '주유소 할인', '40원/L', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO card_benefit (BENEFIT_ID, CARD_ID, BENEFIT_TYPE, BENEFIT_TITLE, BENEFIT_VALUE, CREATED_AT, UPDATED_AT)
VALUES (CARD_BENEFIT_SEQ.nextval, 7, '주유', '농협주유소 NH포인트 적립', '3%', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO card_benefit (BENEFIT_ID, CARD_ID, BENEFIT_TYPE, BENEFIT_TITLE, BENEFIT_VALUE, CREATED_AT, UPDATED_AT)
VALUES (CARD_BENEFIT_SEQ.nextval, 7, '쇼핑', '농협 판매장 NH포인트 적립', '5%', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO card_benefit (BENEFIT_ID, CARD_ID, BENEFIT_TYPE, BENEFIT_TITLE, BENEFIT_VALUE, CREATED_AT, UPDATED_AT)
VALUES (CARD_BENEFIT_SEQ.nextval, 7, '금융', '환전 수수료 우대', '최고 50%', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO card_benefit (BENEFIT_ID, CARD_ID, BENEFIT_TYPE, BENEFIT_TITLE, BENEFIT_VALUE, CREATED_AT, UPDATED_AT)
VALUES (CARD_BENEFIT_SEQ.nextval, 7, '교육', '전화영어 할인', '최대 50%', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO card_benefit (BENEFIT_ID, CARD_ID, BENEFIT_TYPE, BENEFIT_TITLE, BENEFIT_VALUE, CREATED_AT, UPDATED_AT)
VALUES (CARD_BENEFIT_SEQ.nextval, 7, '통신', '해외로밍 할인', '서비스 제공', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO card_benefit (BENEFIT_ID, CARD_ID, BENEFIT_TYPE, BENEFIT_TITLE, BENEFIT_VALUE, CREATED_AT, UPDATED_AT)
VALUES (CARD_BENEFIT_SEQ.nextval, 7, '여가', '국내외 여행패키지 할인', '최대 5%', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO card_benefit (BENEFIT_ID, CARD_ID, BENEFIT_TYPE, BENEFIT_TITLE, BENEFIT_VALUE, CREATED_AT, UPDATED_AT)
VALUES (CARD_BENEFIT_SEQ.nextval, 7, '항공', '국내공항 라운지 무료 이용', '무료', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 올바른POINT체크
INSERT INTO card_benefit (BENEFIT_ID, CARD_ID, BENEFIT_TYPE, BENEFIT_TITLE, BENEFIT_VALUE, CREATED_AT, UPDATED_AT)
VALUES (CARD_BENEFIT_SEQ.nextval, 8, '모든 가맹점', '적립한도 없이 NH포인트 적립', '0.2% ~ 0.7%', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO card_benefit (BENEFIT_ID, CARD_ID, BENEFIT_TYPE, BENEFIT_TITLE, BENEFIT_VALUE, CREATED_AT, UPDATED_AT)
VALUES (CARD_BENEFIT_SEQ.nextval, 8, '공항 라운지', '국제공항 라운지 무료 이용', '무료', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO card_benefit (BENEFIT_ID, CARD_ID, BENEFIT_TYPE, BENEFIT_TITLE, BENEFIT_VALUE, CREATED_AT, UPDATED_AT)
VALUES (CARD_BENEFIT_SEQ.nextval, 8, '금융', '전자금융 수수료 면제', '면제', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


-- 현대카드 ZERO Edition2(할인형)
INSERT INTO card_benefit (BENEFIT_ID, CARD_ID, BENEFIT_TYPE, BENEFIT_TITLE, BENEFIT_VALUE, CREATED_AT, UPDATED_AT)
VALUES (CARD_BENEFIT_SEQ.nextval, 9, '가맹점', '모든 가맹점 할인', '0.7%', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO card_benefit (BENEFIT_ID, CARD_ID, BENEFIT_TYPE, BENEFIT_TITLE, BENEFIT_VALUE, CREATED_AT, UPDATED_AT)
VALUES (CARD_BENEFIT_SEQ.nextval, 9, '생활', '생활필수영역 할인', '1.5%', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO card_benefit (BENEFIT_ID, CARD_ID, BENEFIT_TYPE, BENEFIT_TITLE, BENEFIT_VALUE, CREATED_AT, UPDATED_AT)
VALUES (CARD_BENEFIT_SEQ.nextval, 9, '항공', '비자 영프리미엄 혜택', '제공', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 카드 타이틀과 해당 혜택들을 조회
SELECT 
    c.CARD_TITLE AS 카드이름,
    cb.BENEFIT_TYPE AS 혜택유형,
    cb.BENEFIT_TITLE AS 혜택명,
    cb.BENEFIT_VALUE AS 혜택값
FROM 
    card c
JOIN 
    card_benefit cb
ON 
    c.CARD_ID = cb.CARD_ID
ORDER BY 
    c.CARD_TITLE, cb.BENEFIT_TYPE;

UPDATE card_benefit
SET BENEFIT_TYPE = '카페'
WHERE BENEFIT_TITLE = '카페 포인트 적립';

UPDATE card_benefit
SET BENEFIT_TYPE = '항공'
WHERE BENEFIT_TYPE = '공항 라운지';


select distinct res_member_store_type from CARD_HISTORY;
commit;